  services:
    postgresDB:
      container_name: postgres-sql
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345Do
        POSTGRES_DB: postgres
      ports:
        - 5434:5432
      volumes:
        - postgres:/var/lib/postgres/data

  volumes:
    postgres:

